# Generated by Django 3.1.1 on 2020-09-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostPreview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('md_file_path', models.CharField(max_length=60)),
                ('preview_img_path', models.CharField(max_length=60)),
            ],
        ),
    ]
