# Generated by Django 3.1.1 on 2020-09-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpreview',
            name='description',
            field=models.CharField(default='No description', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpostpreview',
            name='md_file_path',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='blogpostpreview',
            name='preview_img_path',
            field=models.CharField(max_length=1000),
        ),
    ]
