# Generated by Django 3.1.1 on 2020-09-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0002_auto_20200907_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpreview',
            name='md_file',
            field=models.FileField(default='null', max_length=1000, upload_to='blog_markdowns'),
            preserve_default=False,
        ),
    ]
