# Generated by Django 3.1.1 on 2020-09-08 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0003_blogpostpreview_md_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpreview',
            name='md_text',
            field=models.TextField(default='**The post**'),
            preserve_default=False,
        ),
    ]
